name: ds
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.1
  - numpy
  - pandas
  - scikit-learn
  - pyspark=2.4.3
  - jupyter
  - pip
  - pip:
    - tensorflow-gpu==2.0
    - awscli
    - awscli-local