channels: [defaults, conda-forge]
dependencies:
- python=3.7.1
- numpy
- pandas
- scikit-learn
- pyspark=2.4.3
- pylint
- jupyter
- boto3
- pip
- pip: [awscli, awscli-local, black, docker, kubernetes, tensorflow-gpu==2.0, pyyaml]
name: ml
