apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      hostname: spark-master
      containers:
      - name: spark-master
        image: spark:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SPARK_ROLE
          value: master
        - name: SPARK_MASTER_PORT
          value: '7077'
        - name: AWS_ACCESS_KEY_ID
          value: foo
        - name: AWS_SECRET_ACCESS_KEY
          value: bar
        - name: SPARK_PUBLIC_DNS
          value: spark-minikube
        ports:
        - name: master
          containerPort: 7077
        - name: gui
          containerPort: 8080
        volumeMounts:
        # Spark config
        - mountPath: /opt/spark/conf/log4j.properties
          name: spark-config
          subPath: log4j.properties
        - mountPath: /opt/spark/conf/hive-site.xml
          name: spark-config
          subPath: hive-site.xml
        - mountPath: /opt/spark/conf/spark-defaults.conf
          name: spark-config
          subPath: spark-defaults.conf
      volumes:
      # Spark settings volume
      - name: spark-config
        configMap:
          name: spark