---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-edge
  labels:
    app: spark
    role: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: edge
  template:
    metadata:
      labels:
        app: spark
        role: edge
    spec:
      hostname: spark-edge
      containers:
      - name: spark-edge
        image: mlstack-spark
        imagePullPolicy: Never
        env:
        - name: SPARK_ROLE
          value: edge
        - name: SPARK_MASTER_HOST
          value: spark-master
        - name: SPARK_MASTER_PORT
          value: '7077'
        - name: SPARK_LOCAL_IP
          value: spark-edge
        - name: AWS_ACCESS_KEY_ID
          value: foo
        - name: AWS_SECRET_ACCESS_KEY
          value: bar
        ports:
        - containerPort: 31000
        - containerPort: 31001
        volumeMounts:
        # Spark config files
        - mountPath: /opt/spark/conf/log4j.properties
          name: spark-config
          subPath: log4j.properties
        - mountPath: /opt/spark/conf/hive-site.xml
          name: spark-config
          subPath: hive-site.xml
        - mountPath: /opt/spark/conf/spark-defaults.conf
          name: spark-config
          subPath: spark-defaults.conf
      volumes:
      # Spark settings volume
      - name: spark-config
        configMap:
          name: spark
---
apiVersion: v1
kind: Service
metadata:
  name: spark-edge
spec:
  selector:
    app: spark
    role: edge
  ports:
    - name: driver
      port: 31000
      targetPort: 31000
    - name: block-manager
      port: 31001
      targetPort: 31001
    - name: app-ui
      port: 4040
      targetPort: 4040
