kind: PersistentVolume
apiVersion: v1
metadata:
  name: spark-cache
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/spark/cache
