kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spark-cache
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: spark-cache