apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      hostname: localstack
      containers:
      - name: localstack
        image: localstack/localstack
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICES
          value: s3:4572,dynamodb:4569
        - name: DEBUG
          value: debug
        - name: DATA_DIR
          value: /tmp/localstack/data
        - name: PORT_WEB_UI
          value: '8080'
        ports:
        - containerPort: 4572
        - containerPort: 4569
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tmp/localstack
          name: data
      volumes:
      - name: data
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: localstack-gui
spec:
  type: NodePort
  selector:
    app: localstack
  ports:
  - name: gui
    protocol: TCP
    port: 8080
    nodePort: 30079
---
kind: Service
apiVersion: v1
metadata:
  name: localstack
spec:
  type: NodePort
  selector:
    app: localstack
  ports:
  - name: s3
    protocol: TCP
    port: 4572
    nodePort: 30572
  - name: dynamodb
    protocol: TCP
    port: 4569
    nodePort: 30569