kind: Service
apiVersion: v1
metadata:
  name: localstack
spec:
  type: NodePort
  selector:
    app: localstack
  ports:
  - name: s3
    protocol: TCP
    port: 4572
    nodePort: 30572
  - name: dynamodb
    protocol: TCP
    port: 4569
    nodePort: 30569
